AWSTemplateFormatVersion: "2010-09-09"

Description: ECR Private Repository resource

Resources:
  CustomersServiceRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "adot-training/customers-service"
      ImageScanningConfiguration: 
        ScanOnPush: true

  VisitsServiceRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "adot-training/visits-service"
      ImageScanningConfiguration: 
        ScanOnPush: true
  
  VetsServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "adot-training/vets-service"
      ImageScanningConfiguration: 
        ScanOnPush: true

  PetClinicUIRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "adot-training/petclinic-ui"
      ImageScanningConfiguration: 
        ScanOnPush: true

  CustomersServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /ecs/CustomerService
      RetentionInDays: 7

  VisitsServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /ecs/VisitsService
      RetentionInDays: 7

  VetsServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /ecs/VetsService
      RetentionInDays: 7

  PetClinicUIeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /ecs/PetClinicUI
      RetentionInDays: 7