AWSTemplateFormatVersion: "2010-09-09"

Description: ECR Private Repository resource

Resources:
  CustomersServiceRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "adot-training/customers-service"
      ImageScanningConfiguration: 
        ScanOnPush: true

  VisitsServiceRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "adot-training/visits-service"
      ImageScanningConfiguration: 
        ScanOnPush: true
  
  VetsServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "adot-training/vets-service"
      ImageScanningConfiguration: 
        ScanOnPush: true

  PetClinicUIRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "adot-training/petclinic-ui"
      ImageScanningConfiguration: 
        ScanOnPush: true