AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster Resource
Parameters:
  VpcId:
    Type: String
  PublicSubnet1Id:
    Type: String
  PublicSubnet2Id:
    Type: String
    
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: ADOT-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
         ExecuteCommandConfiguration:
            Logging: DEFAULT

  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ADOT-task-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/AmazonPrometheusRemoteWriteAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  TasksSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Fargate Tasks Security Group
      VpcId: !Ref VpcId

  TasksSecurityGroupIngressRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref TasksSecurityGroup
      IpProtocol: -1
      CidrIp: 10.192.0.0/16

  TasksSecurityGroupIngressRule2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      FromPort: "80"
      ToPort: "80"
      GroupId: !Ref TasksSecurityGroup
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ADOT-NLB
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      Scheme: internet-facing
      Type: network
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: ADOT-targetgroup
      VpcId: !Ref VpcId
      Port: 80
      Protocol: TCP
      TargetType: ip